"""The node reproduces the backend's golden vectors, field for field.

⛔ WHY THIS FILE IS THE MOST IMPORTANT TEST IN THIS REPO. `src/merkle.py` is a SECOND
implementation of formats the backend also builds. The backend's own docstring states the
cost of the two disagreeing:

    "a disagreement refuses every signature and the failure is a fleet-wide outage,
     not a test."

`tests/vectors/node_v2_vectors.json` is generated by running the BACKEND's builders and
committed byte-identically in both repos. If this file passes, the two halves agree on
every leaf format, the merkle construction, the v2 block hash and the signed pre-image.
If it fails, the fleet would have refused every block — here instead.
"""
from __future__ import annotations

import json
import pathlib

import pytest

from src import merkle

VECTORS = pathlib.Path(__file__).resolve().parent / "vectors" / "node_v2_vectors.json"


def _cases():
    data = json.loads(VECTORS.read_text(encoding="utf-8"))
    return data["cases"]


def test_the_vector_file_is_present_and_populated():
    """Entry witness. Every assertion below iterates the case list — an empty or missing
    file would make all of them pass while proving nothing."""
    assert VECTORS.is_file(), (
        f"{VECTORS} is missing. It is generated by the backend "
        "(`python -m scripts.gen_node_v2_vectors`) and copied here byte-identically.")
    cases = _cases()
    assert len(cases) >= 5, f"only {len(cases)} vectors; the edge cases are missing"
    for c in cases:
        assert c.get("why"), f"{c['name']} has no stated reason"


@pytest.mark.parametrize("case", _cases(), ids=lambda c: c["name"])
def test_the_node_reproduces_every_expected_field(case):
    g, e = case["given"], case["expected"]
    got = merkle.roots_from_contents(g)

    #: the leaf payloads first — a root that matches by luck with a wrong payload is
    #: not agreement, and the payload is where two implementations actually diverge
    assert got["event_leaf_payloads"] == e["event_leaf_payloads"], (
        f"{case['name']}: event leaf payload differs from the backend's.\n"
        f"  why this case exists: {case['why']}")
    assert got["tx_leaf_payloads"] == e["tx_leaf_payloads"], (
        f"{case['name']}: tx leaf payload differs from the backend's.\n"
        f"  why this case exists: {case['why']}")

    for k in ("match_root", "event_root", "tx_root", "match_count", "event_count", "tx_count"):
        assert got[k] == e[k], f"{case['name']}: {k} differs ({got[k]!r} != {e[k]!r})"

    block_hash = merkle.hash_block_v2(
        g["number"], g["prev_hash"], got["match_root"], got["event_root"], got["tx_root"],
        got["match_count"], got["event_count"], got["tx_count"],
        g["hash_timestamp"], g["creator_id"])
    assert block_hash == e["block_hash"], (
        f"{case['name']}: the recomputed v2 block hash differs. A node would refuse this "
        f"block as tampered when it is not.")

    assert merkle.validation_payload(
        g["number"], block_hash, g["prev_hash"], got["match_root"], got["event_root"],
        got["tx_root"], got["match_count"], got["event_count"], got["tx_count"],
        g["hash_timestamp"], g["creator_id"]) == e["validation_payload"], (
        f"{case['name']}: the signed pre-image differs from the backend's verifier. "
        f"Every signature this node produced would be rejected.")


def test_the_signed_preimage_is_NOT_the_block_hash_preimage():
    """⛔ `tv2|` not `v2|`. Signing the block-hash pre-image would be signing a string the
    platform can produce without us — and whose digest is already public as the block
    hash. The two must never collide."""
    c = _cases()[0]
    g, e = c["given"], c["expected"]
    assert e["validation_payload"].startswith("tv2|")
    assert not e["validation_payload"].startswith("v2|")
    assert e["block_hash"] not in e["validation_payload"].split("|")[0]
    #: and the block hash is INSIDE the signed string, so a signature cannot be replayed
    #: onto a different block whose contents happen to hash the same way
    assert e["block_hash"] in e["validation_payload"]


def test_an_empty_leaf_set_is_the_shared_constant():
    """A contentless block's three roots are all sha256("empty"). Reproduced, not treated
    as an error — and it is why possessing them proves nothing, which is the backend's
    reason for refusing to stamp such a block v2."""
    empty = next(c for c in _cases() if "contentless" in c["name"])["expected"]
    assert empty["match_root"] == empty["event_root"] == empty["tx_root"]
    assert merkle.merkle_root([]) == empty["match_root"]


def test_a_zero_field_renders_as_0_not_as_a_decimal():
    """The coalescing edge. `_grams or 0` makes a falsy zero render `0`, never `0.000`.
    A node that formatted the number it received would diverge on exactly the blocks
    carrying none of the metal."""
    case = next(c for c in _cases() if "zero" in c["name"])
    payloads = merkle.roots_from_contents(case["given"])["event_leaf_payloads"]
    assert payloads == case["expected"]["event_leaf_payloads"]
    assert "|0|" in payloads[0], f"zero did not render as 0: {payloads[0]!r}"


# ═══════════════════════════════════════════════════════════════════════════
#  A MALFORMED RESPONSE IS REFUSED, NOT GUESSED
# ═══════════════════════════════════════════════════════════════════════════

def test_a_missing_field_is_REFUSED_rather_than_defaulted():
    """⛔ A node that defaults a missing field computes a PLAUSIBLE root from values it
    never saw, and then signs it. Refusing is the only honest answer.

    An earlier draft coalesced (`e.get('grams') ... else 0`). Mutation proved that branch
    could not even be reached: the endpoint already applies the backend's coalescing, so
    these keys always arrive as strings. A second coalescing that can never fire can only
    drift away from the first.
    """
    good = {"id": "e1", "event_hash": "0x" + "11" * 32, "event_type": "MINT",
            "metal": "Gold", "grams": "1.000", "vault_key": "VK-1"}
    assert merkle.event_leaf_payload(good)          # entry witness: the good shape works

    for missing in ("id", "event_hash", "event_type", "metal", "grams", "vault_key"):
        bad = {k: v for k, v in good.items() if k != missing}
        with pytest.raises(merkle.ContentsMalformed) as ei:
            merkle.event_leaf_payload(bad)
        assert missing in str(ei.value), f"the refusal does not name {missing!r}"

    for nulled in ("grams", "metal"):
        bad = dict(good, **{nulled: None})
        with pytest.raises(merkle.ContentsMalformed):
            merkle.event_leaf_payload(bad)


def test_a_malformed_TX_leaf_is_refused_too():
    """The tx leaf carries two amount fields; both must be present."""
    good = {"id": "t1", "tx_hash": "0x" + "22" * 32, "tx_type": "TRADE", "metal": "Gold",
            "grams": "1.000", "total_grams": "1.000",
            "from_vault_key": "VK-1", "to_vault_key": "VK-2"}
    assert merkle.tx_leaf_payload(good)

    for missing in ("grams", "total_grams", "from_vault_key", "to_vault_key"):
        bad = {k: v for k, v in good.items() if k != missing}
        with pytest.raises(merkle.ContentsMalformed):
            merkle.tx_leaf_payload(bad)


def test_roots_from_contents_never_READS_a_served_root():
    """⛔ The endpoint deliberately withholds event_root and tx_root — building them is
    the work that separates validating from attesting. If a future response carried them,
    accepting one would silently reduce this node to a self-reported version string."""
    case = _cases()[0]
    poisoned = dict(case["given"],
                    event_root="0x" + "de" * 32,
                    tx_root="0x" + "ad" * 32,
                    match_root="0x" + "be" * 32)
    got = merkle.roots_from_contents(poisoned)
    for k in ("match_root", "event_root", "tx_root"):
        assert got[k] == case["expected"][k], (
            f"{k} came back as the SERVED value — the node is trusting a root instead of "
            f"computing it, which is exactly what v2 exists to stop")
        assert got[k] != poisoned[k]
