"""Leaf payloads, merkle roots and the v2 block hash — the node's half of the contract.

⛔ THIS IS A SECOND IMPLEMENTATION, DELIBERATELY, AND THAT IS THE RISK.

The backend builds these same strings in `app/services/blockchain/sealing.py` and
`block_engine.py`. This repo is separate and public and cannot import them, so the
formats necessarily exist twice. The backend's own docstring states what a disagreement
costs:

    "a disagreement refuses every signature and the failure is a fleet-wide outage,
     not a test."

What holds the halves together is `tests/vectors/node_v2_vectors.json` — generated by
running the BACKEND's builders, committed byte-identically in both repos, and asserted
here by `tests/test_vectors.py`. The backend's cross-repo seam job compares the two
copies. Change a format on either side without regenerating and the seam goes red before
a node ever refuses a block.

⚠️ EVERY SEPARATOR AND EVERY COALESCE IS PART OF THE CONTRACT. `_grams or 0` is not a
tidy-up: a zero renders as `0`, never `0.000`, because a Decimal zero is falsy. The
backend's endpoint mirrors that with `str(r[2] or 0)`. Reformatting the number you
received would diverge on exactly the blocks that carry none of the metal.
"""
from __future__ import annotations

import hashlib
from typing import Iterable, List


def sha256(data: str) -> str:
    """SHA-256 over UTF-8, returned 0x-prefixed. Mirrors block_engine.sha256."""
    return "0x" + hashlib.sha256(data.encode("utf-8")).hexdigest()


def merkle_root(hashes: Iterable[str]) -> str:
    """Mirrors block_engine.merkle_root.

    ⚠️ An EMPTY list is `sha256("empty")` — a CONSTANT, and the same one for all three
    trees. A contentless block therefore has three identical roots, which is real and
    must be reproduced rather than treated as an error. (It is also why the backend
    refuses to stamp such a block v2: possessing that constant proves nothing.)
    """
    nodes = [h.replace("0x", "") for h in hashes]
    if not nodes:
        return sha256("empty")
    while len(nodes) > 1:
        if len(nodes) % 2 == 1:
            nodes.append(nodes[-1])          # odd level duplicates its last node
        nodes = [
            hashlib.sha256((nodes[i] + nodes[i + 1]).encode()).hexdigest()
            for i in range(0, len(nodes), 2)
        ]
    return "0x" + nodes[0]


class ContentsMalformed(ValueError):
    """The `/contents` response is not shaped like the contract.

    ⛔ RAISED, NEVER COALESCED. An earlier draft defaulted missing fields, which meant a
    malformed response produced a *plausible* root instead of a refusal — and a node that
    signs a root computed from guessed values is attesting to something it did not see.
    Mutation showed the defaulting could not even be exercised: the endpoint already
    applies the backend's coalescing (`str(r[2] or 0)`), so these keys always arrive as
    strings. A second coalescing that can never fire can only drift away from the first.
    """


def _field(d: dict, key: str, where: str) -> str:
    if key not in d:
        raise ContentsMalformed(f"{where}: missing field {key!r} — refusing to guess it")
    v = d[key]
    if v is None:
        raise ContentsMalformed(f"{where}: field {key!r} is null — refusing to guess it")
    return str(v)


def match_leaf_payload(m: dict) -> str:
    """Mirrors sealing.match_leaf_payload_from_fields, from the dict `/contents` serves.

    Backend: f"MATCH|{id}|{buy_order_id}|{sell_order_id}|{metal}|{quantity_grams}|"
             f"{price_per_gram}|{matched_at}"

    ⚠️ Until 2026-09-21 the endpoint served this leaf as a FINISHED STRING while event
    and tx leaves came as fields — so a node verified those two formats itself and took
    this one on trust, for no principled reason. All three are fields now and the node
    builds every payload, so a change to any leaf format is caught here rather than
    signed.

    ⚠️ `buy_order_id` can legitimately be the STRING "None": the backend interpolates the
    value directly and `f"{None}"` renders "None", which production has already hashed
    into sealed blocks. It is served as-is and used as-is — coalescing it to empty here
    would compute a root no block ever had.
    """
    w = "match leaf"
    return (
        f"MATCH|{_field(m,'id',w)}|{_field(m,'buy_order_id',w)}"
        f"|{_field(m,'sell_order_id',w)}|{_field(m,'metal',w)}"
        f"|{_field(m,'quantity_grams',w)}|{_field(m,'price_per_gram',w)}"
        f"|{_field(m,'matched_at',w)}"
    )


def event_leaf_payload(e: dict) -> str:
    """Mirrors sealing.event_leaf_payload, from the dict `/contents` serves.

    Backend: f"E|{_id}|{_eh or ''}|{_etype or ''}|{_metal or ''}|{_grams or 0}|{_vk or ''}"

    ⚠️ THE ENDPOINT HAS ALREADY APPLIED THAT COALESCING — it serves `str(r[2] or 0)`, so a
    zero arrives as the string "0" and never as "0.000". This function therefore does NOT
    coalesce again; it formats exactly what it received, and refuses a response that is
    missing a field rather than inventing one.
    """
    w = "event leaf"
    return (
        f"E|{_field(e,'id',w)}|{_field(e,'event_hash',w)}|{_field(e,'event_type',w)}"
        f"|{_field(e,'metal',w)}|{_field(e,'grams',w)}|{_field(e,'vault_key',w)}"
    )


def tx_leaf_payload(t: dict) -> str:
    """Mirrors sealing.tx_leaf_payload, from the dict `/contents` serves."""
    w = "tx leaf"
    return (
        f"T|{_field(t,'id',w)}|{_field(t,'tx_hash',w)}|{_field(t,'tx_type',w)}"
        f"|{_field(t,'metal',w)}|{_field(t,'grams',w)}|{_field(t,'total_grams',w)}"
        f"|{_field(t,'from_vault_key',w)}|{_field(t,'to_vault_key',w)}"
    )


def hash_block_v2(number: int, prev_hash: str, match_root: str, event_root: str,
                  tx_root: str, match_count: int, event_count: int, tx_count: int,
                  hash_timestamp: str, creator_id: str) -> str:
    """Mirrors block_engine.hash_block_v2.

    ⚠️ `hash_timestamp` must be the EXACT string the backend persisted, never a
    re-serialisation of a parsed datetime — that is the v1 defect v2 exists to fix.
    """
    return sha256(
        f"v2|{number}|{prev_hash}|{match_root}|{event_root}|{tx_root}"
        f"|{match_count}|{event_count}|{tx_count}"
        f"|{hash_timestamp}|{creator_id}"
    )


def validation_payload(number: int, block_hash: str, prev_hash: str, match_root: str,
                       event_root: str, tx_root: str, match_count: int, event_count: int,
                       tx_count: int, hash_timestamp: str, creator_id: str) -> str:
    """The exact string a validating node signs. Mirrors sealing.validation_payload.

    ⚠️ `tv2|` NOT `v2|`. `hash_block_v2` already builds a `v2|…` string whose digest is
    public as the block hash; signing that would be signing something the platform can
    produce without us. The prefix differs so the two pre-images can never collide, and
    `block_hash` is included so a signature cannot be replayed onto another block.
    """
    return (
        f"tv2|{number}|{block_hash}|{prev_hash}|{match_root}|{event_root}|{tx_root}"
        f"|{match_count}|{event_count}|{tx_count}|{hash_timestamp}|{creator_id}"
    )


def roots_from_contents(contents: dict) -> dict:
    """Recompute all three roots from a `/contents` response. No root is ever READ.

    ⛔ The endpoint deliberately does NOT serve `event_root` or `tx_root`: building them
    is the work that distinguishes validating from attesting. If a future response
    carries them, they are still ignored here — accepting a served root would reduce
    this node to a self-reported version string.
    """
    mt = [match_leaf_payload(m) for m in (contents.get("match_leaves") or [])]
    ev = [event_leaf_payload(e) for e in (contents.get("event_leaves") or [])]
    tx = [tx_leaf_payload(t) for t in (contents.get("tx_leaves") or [])]
    return {
        "match_leaf_payloads": mt,
        "match_root": merkle_root([sha256(p) for p in mt]),
        "event_root": merkle_root([sha256(p) for p in ev]),
        "tx_root": merkle_root([sha256(p) for p in tx]),
        "match_count": len(mt),
        "event_count": len(contents.get("event_leaves") or []),
        "tx_count": len(contents.get("tx_leaves") or []),
        "event_leaf_payloads": ev,
        "tx_leaf_payloads": tx,
    }
